### ISSUE TITLE
Issues with XEOX PRO ANALOG GAMEPAD

### ISSUE THREAD

**Issue by pixonte** [henriforshort/hinput#7]
For reference, here's the device: https://www.speedlink.com/en/Gaming/XEOX-PRO-ANALOG-GAMEPAD-USB-BLACK.html The device supports 2 modes - XInput und DirectInput® and in XInput it doesn't do anything. In DirectInput there are a couple of issues too:
- Vibration does not work at all. 
- Triggers act as "back" and "start"

Windows 10 64, Unity 2019.2.12

And thanks a lot for this nice tool and its simple programming interface!

**Comment by henriforshort** [comment]
Hi there,

I don't know this device, but XInput drivers should be supported by Hinput... I'm not sure what I can do for you.

I'm working on a general compatibility improvement that might fix that, but it won't be out before a few more days/weeks.

If you wish, in the meantime I can send you a modified version of the plugin that switch some buttons with each other ? It would only work on your controller though.

**Comment by pixonte** [comment]
hi, thanks for the prompt responce. There's no immediate need for a fix actually, just wanted to to let you know the issue exists with that particular hardware.

**Comment by henriforshort** [comment]
Update on this issue: Hinput supports XInput controllers, but not DirectInput (not possible with the old Input Manager). 

However I have released the "general compatibility improvement" as a paid version called Hinput Pro, that is based on the new Input System of Unity. It supports both these drivers properly, as well as vibration (www.tiny.cc/hinput-pro).
